- name: install squid 
  yum:
    name: squid
    state: present
    

- name: staerted squid 
  service:
    name: squid
    state: started
    enabled: yes 

- name: Remove default file squid.conf default
  become: yes
  command:  rm -rf /etc/squid/squid.conf
  
- name: Upload default squid.conf 
  become: yes
  copy: 
    src: files/squid.conf 
    dest: /etc/squid/ 
    mode: 0644

- name: restarted squid e finish process
  service:
    name: squid
    state: restarted     

- name: state squid
  shell: "systemctl status squid | sed -n 3p | awk '/active/ {print $2}'"        
  register: service_status

- debug: 
    var: service_status.stdout          

- name: check start 
  command: systemctl start squid
  when: service_status.stdout == "inactive"     